sudo : required
services: 
  - docker

before_install: 
  - docker build -t cresphontes/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true cresphontes/react-test npm test -- --coverage  

after_success:
  - docker build -t cresphontes/multi-client ./client  
  - docker build -t cresphontes/multi-nginx ./nginx  
  - docker build -t cresphontes/multi-server ./server  
  - docker build -t cresphontes/multi-worker ./worker  

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push cresphontes/multi-client 
  - docker push cresphontes/multi-nginx
  - docker push cresphontes/multi-server
  - docker push cresphontes/multi-worker 

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: Multi-Docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-2-273845791300
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: 
    secure: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY    
  
