sudo : required
services: 
  - docker

  before-install: 
    - docker build -t aykutkaragoz/react-test -f ./client/Dockerfile.dev ./client

  script:
    - docker run -e CI=true aykutkaragoz/react-test npm test -- --covarage  

  after-success:
    - docker build -t aykutkaragoz/multi-client ./client  
    - docker build -t aykutkaragoz/multi-nginx ./nginx  
    - docker build -t aykutkaragoz/multi-server ./server  
    - docker build -t aykutkaragoz/multi-worker ./worker  

    echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password -stdin

    - docker push aykutkaragoz/multi-client 
    - docker push aykutkaragoz/multi-nginx
    - docker push aykutkaragoz/multi-server
    - docker push aykutkaragoz/multi-worker 
  
